### PR TITLE
added range for bartimaeusnek

### PR DESCRIPTION
**Pull request by bartimaeusnek**
would be great if i could get this range for my mod crops++, my fork of EMT, and some other small addons

### CODE REVIEW

**Review by jaskarth — CHANGES_REQUESTED** [review]
You should use 12501 - 13000

**Comment by draknyte1** [comment]
I agree with Code, although curious as to why you skipped that range?

**Comment by bartimaeusnek** [comment]
but that range is already reserved...

**Comment by jaskarth** [comment]
It's for whoever asks next. In this case, it's you.

**Review by jaskarth — APPROVED** [review]

**Review by draknyte1 — APPROVED** [review]

**Pull request merged**
