### PR TITLE
Fixed GT5 Build process

### PR DESCRIPTION
**Pull request by draknyte1**
Fixed Build Script.
Fixed IC2C compile issue.
Fixed Radiation effect using a statc potion ID.
Removed IE, Magneticraft, TiCon and Translocators as compile requirements.

### CODE REVIEW

**Comment by MauveCloud** [comment]
Are you still able to build this?  When I try, I get the following error:
```
* What went wrong:
A problem occurred evaluating root project 'GT5-Unofficial-Ex-Fix-Build-Process'.
> Failed to apply plugin [id 'forge']
   > You must set the Minecraft Version!
      > java.lang.NullPointerException (no error message)
```
Only I'm not sure whether the problem is specific to my machine/configuration.

**Comment by draknyte1** [comment]
It built from a fresh clone of my branch. I can only assume it works..

**Comment by MauveCloud** [comment]
Okay, I got past that by copying the Gradle wrapper from Forestry 3.6, so I'm guessing ForgeGradle 1.2-snapshot isn't fully compatible with newer builds of Gradle (I have 4.10.2 installed, idk what version you're running).  I ran into some other issues with the build that seem easier to address, but in the meantime might I suggest adding a Gradle wrapper to the GT5u project?

**Comment by leagris** [comment]
I use the gradle wrapper 4.0

```sh
./gradlew --version

------------------------------------------------------------
Gradle 4.0
------------------------------------------------------------

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_232 (Private Build 25.232-b09)
OS:           Linux 5.3.0-23-generic amd64
```

I think it works up to Gradle 4.2, but 4.10 is definitely too high and incompatible with forgeGradle. It will fail to detect Minecraft version.

I also suggest moving all dependencies to a directory, even hosting the files in the repository before the remaining few public repositories vanishes.

I have this in my build.properties:
```gradle
    flatDir {
        dirs 'libs'
    }
```

With the following hosted into the libs dir:
```none
appliedenergistics2-rv3-beta-6-dev.jar
CoFHCore-[1.7.10]3.1.4-329-dev.jar
CoFHLib-[1.7.10]1.2.1-185-dev.jar
forestry_1.7.10-4.2.10.58-dev.jar
GalacticraftCore-Dev-1.7-3.0.12.504.jar
IC2NuclearControl-2.3.4a.jar
ImmersiveEngineering-0.7.7-deobf.jar
industrialcraft-2-2.2.790-experimental-api.jar
industrialcraft-2-2.2.790-experimental-dev.jar
magneticraft-0.6.1-final.jar
Railcraft-1.7.10-9.4.0.0.jar
Thaumcraft-1.7.10-4.2.1.0-api.zip
Thaumcraft-1.7.10-4.2.3.5.jar
```

**Comment by draknyte1** [comment]
Libs are NOT required. You’ve even got fucking duplicates, so please don’t suggest stupid shit. Gradle versioning isn’t GT specific, I can note it, but it’s not really on us to provide the wrapper. 

OvermindDL1’s Maven repository will outlast Forge and probably MC modding, lol.  I’m not hosting libs when is already being done. If forge goes down, NOBODY can build mods. Except us and the other few using OM’s repo.

**Pull request merged**
