### PR TITLE
Updated NEI for Assembly Line scanner recipes, small tweaks.

### PR DESCRIPTION
**Pull request by draknyte1**
WIP~

### CODE REVIEW

**Comment by draknyte1** [comment]
Done~

Feature Request from https://github.com/Blood-Asp/GT5-Unofficial/issues/1515

**Comment by draknyte1** [comment]
More To-Do.

**Comment by draknyte1** [comment]
I have to update build.gradle again.
```
Ender core version is 1.7.10-0.2.0.39_beta, 
eio version is 1.7.10-2.3.0.430_beta
```

**Comment by Blood-Asp** [comment]
Is this ready to merge?

**Comment by draknyte1** [comment]
Nah, just want me to merge it when it’s done?
Gotta merge in some of the further changes we continued on in NH’s fork

**Comment by Blood-Asp** [comment]
I would like to merge asap to make a new build to upload. Is the current state ready to merge? 

Testing the updated gradle build script got me an error. Not sure if my error, one of the linked stuff broken or script not working:

```
C:\Users\blood\MC\GT5-Unoffical>gradlew setupDecompWorkspace --refresh-dependencies

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\blood\MC\GT5-Unoffical\build.gradle' line: 86

* What went wrong:
A problem occurred evaluating root project 'GT5-Unoffical'.
> Could not find method compileOnly() for arguments [net.sengir.forestry:forestry_1.7.10:4.2.16.64:dev] on root project 'GT5-Unoffical'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 19.113 secs
```

**Pull request closed without merging**
