### PR TITLE
Add config for Small Boiler Automation

### PR DESCRIPTION
**Pull request by redmage17**
Default is off

### CODE REVIEW

**Review by draknyte1 — CHANGES_REQUESTED** [review]
Your fucking Boolean logic is backwards, No.

**Review by draknyte1 — CHANGES_REQUESTED** [review]
I guess you don't understand how booleans fucking work dude.

**Comment by Blood-Asp** [comment]
I guess i have to give a hint:
```
if(value) return true
else return false 
```

is the same as 

`return value`

the other stuff was fine.

**Comment by draknyte1** [comment]
You didn't need to give a hint because his PR is already fine?
Learn to read fucktard.

**Comment by MauveCloud** [comment]
@draknyte1 did you seriously just insult Blood Asp (with very crude language I might add), who afaik is still in charge of GT5u?  redmage17 had already fixed the logic problem by the time Blood Asp saw it, in case you hadn't noticed.

**Comment by Blood-Asp** [comment]
well yes, on mobile that was the only issue i saw but not that there was another push beween.
so that is just another thing to fix. works this way but should better be cleaned up.

and sry, that level of crude language? all you will get that way is more hate and certainly not improved code...

**Comment by draknyte1** [comment]
@MauveCloud, your opinion is moot. 
@Blood-Asp learn to page refresh. Then you don't need to give useless opinions which make you look stupid. 

This PR was discussed and resolved outside of GitHub with Red and the final result can only be improved by simply returning the variable, as opposed to checking and returning a seperate Boolean. The JVM probably inlines this during compilation regardless.

**Review by draknyte1 — APPROVED** [review]

**Pull request merged**
