### PR TITLE
Configed metal blocks

### PR DESCRIPTION
**Pull request by redmage17**
Added config for removal of shapeless recipes for metal blocks. Tested it works.

### CODE REVIEW

**Comment by redmage17** [comment]
It allows you to config whether or not your need to use the compressor to create metal blocks from ingots.

**Review by draknyte1 — CHANGES_REQUESTED** [review]
So, a few things.
Bad use of a Scala import.
mEasierCasings defaults to true, should be false.
Youve changed small boiler automation, thats not going to be accepted. Make it a config option if you want it flexible.

I prefer you make each change as a seperate PR instead of bundling them together.

**Comment by redmage17** [comment]
I didn't realize the pull request would update as I worked with the fork have been testing a few things, let me rewrite this

**Comment by redmage17** [comment]
Also where is the bad Scala import? I can't find any changes that I made that should use Scala to my knowledge.

**Comment by redmage17** [comment]
Issues look to be fixed

**Comment by tomasbrod** [comment]
I suggest you to either create a new PR or remove the unwanted commits from this BRANCH (usign git reset --hard, or rebase -i) and push --force.

**Pull request closed without merging**
