### PR TITLE
May or may not fix #565

### LINKED ISSUE #565: Assembly line books: item names not shown correctly on server
I started making the data sticks/part list books on the IT2 server. Sadly everything which should e.g. show "Electric Motor (LuV)" reads something like "gt.metaitem.01.32606". This happens to the description of the book or datastick, but also inside the books itself. The strangest thing is that it works perfectly fine in SP.

### PR DESCRIPTION
**Pull request by leagris**
Just an idea

### CODE REVIEW

**Comment by Blood-Asp** [comment]
Might possibly work. Needs someone to test this who has a server... But might in the worst case even crash...
I will merge and make an build of it. Do you have a server to test or should i ask in the forum?

**Comment by Blood-Asp** [comment]
https://1drv.ms/u/s!AmaOa6IoyYxHlh1xt-LEQh5Oqwtz

**Comment by leagris** [comment]
Have a server to test if you have a build.

**Comment by Blood-Asp** [comment]
Build is linked above^^

**Comment by leagris** [comment]
It just works :)

``` YAML
Inventory: (TagList)
  (TagCompound)
     Count: 1
     Slot: 0
     Damage: 32708
     id: 5692
     tag: (TagCompound)
        eu: 6000
        time: 600
        author: Assembly Line Recipe Generator
        title: Field Generator (LuV) Construction Data
        pages: (TagList)
           Constructionplan for 1 Field Generator (LuV). Needed EU/t: 6000 Productiontime: 30
           Input Bus 1: 1 HSS-G Frame Box
           Input Bus 2: 6 HSS-G Plate
           Input Bus 3: 1 Quantum Star
           Input Bus 4: 4 Emitter (LuV)
           Input Bus 5: 8 Energy Flow Circuit
           Input Bus 6: 64 Fine Osmium Wire
           Input Bus 7: 64 Fine Osmium Wire
           Input Bus 8: 64 Fine Osmium Wire
           Input Bus 9: 64 Fine Osmium Wire
           Input Bus 10: 8 1x Yttrium Barium Cuprate Cable
           Input Hatch 1: 576L Molten Soldering Alloy
        0: (TagCompound)
           Count: 1
           Damage: 4468
           id: 912
        1: (TagCompound)
           Count: 6
           Damage: 17372
           id: 5692
        2: (TagCompound)
           Count: 1
           Damage: 32725
           id: 5692
        3: (TagCompound)
           Count: 4
           Damage: 32685
           id: 5692
        4: (TagCompound)
           Count: 8
           Damage: 32706
           id: 5692
        5: (TagCompound)
           Count: 64
           Damage: 19083
           id: 5693
        6: (TagCompound)
           Count: 64
           Damage: 19083
           id: 5693
        7: (TagCompound)
           Count: 64
           Damage: 19083
           id: 5693
        8: (TagCompound)
           Count: 64
           Damage: 19083
           id: 5693
        9: (TagCompound)
           Count: 8
           Damage: 1766
           id: 912
        f0: (TagCompound)
           Amount: 576
           FluidName: molten.solderingalloy
        output: (TagCompound)
           Count: 1
           Damage: 32675
           id: 5692
```

capture du 2016-08-24 00-52-06

**Pull request merged**
