### PR TITLE
Added new function to GT scanner

### PR DESCRIPTION
**Pull request by Dimach**
Print voltage and amperage of electric cable at last second.

### CODE REVIEW

**Comment by Technus** [comment]
proper way is to
just  override this in GT_MetaPipeEntity_Cable class
```java
    @Override
    public boolean isGivingInformation() {
        return true;
    }

    @Override
    public String[] getInfoData() {
        return new String[]{
                //EnumChatFormatting.BLUE + mName + EnumChatFormatting.RESET,
                "Heat: "+
                        EnumChatFormatting.RED+ mOverheat +EnumChatFormatting.RESET+" / "+EnumChatFormatting.YELLOW+ mMaxOverheat + EnumChatFormatting.RESET,
                "Max Load (1t):",
                EnumChatFormatting.GREEN + Integer.toString(mTransferredAmperageOK) + EnumChatFormatting.RESET +" A / "+
                        EnumChatFormatting.YELLOW + Long.toString(mAmperage) + EnumChatFormatting.RESET +" A",
                "Max EU/p (1t):",
                EnumChatFormatting.GREEN + Long.toString(mTransferredVoltageOK) + EnumChatFormatting.RESET +" EU / "+
                        EnumChatFormatting.YELLOW + Long.toString(mVoltage) + EnumChatFormatting.RESET +" EU",
                "Max Load (20t): "+
                    EnumChatFormatting.GREEN + Integer.toString(mTransferredAmperageLast20OK) + EnumChatFormatting.RESET +" A",
                "Max EU/p (20t): "+
                    EnumChatFormatting.GREEN + Long.toString(mTransferredVoltageLast20OK) + EnumChatFormatting.RESET +" EU"
        };
    }
```

Rest of what i did there is in the GTNH fork

**Comment by mura3277** [comment]
@Dimach It would be great if you could add this via the proper method like how @Technus has done it.

**Comment by Technus** [comment]
Or just copypaste it from our fork to save me work

**Comment by mura3277** [comment]
I was asking @Dimach to do this, not you :D

**Comment by Technus** [comment]
ik just pointing him in the direction

**Comment by Dimach** [comment]
@Muramasa- , @Technus method getInfoData used by NuclearControl panels to display information, i write my code right because i dont want allow reading info directly from wires to display, its function added ONLY for scanner.

**Comment by mura3277** [comment]
Future info: This PR implements #189

**Comment by mura3277** [comment]
@Dimach Ah I understand. It wouldn't a terrible idea to allow NC panels to display EU/t no?

**Comment by Dimach** [comment]
@Muramasa- its good idea, but not directly from wires. In my other PR https://github.com/Blood-Asp/GT5-Unofficial/pull/1176 i added that feature to batbuffer, so i think its enough.

**Comment by Technus** [comment]
@Dimach the nuclear control panel doesnt read it from the wire either, it reads it trough the adapter

**Review by draknyte1 — APPROVED** [review]
Seems okay to me, but lets see what Mura says.

**Pull request merged**
