### PR TITLE
Fixing efficiency calculation operator precedence.

### PR DESCRIPTION
**Pull request by Technus**
This will allow more eu to b eproduced by simple matter of:

EUt_Eff/10000 -> EUt_(Eff/10000)

Saving a lot of Integer space.

### CODE REVIEW

**Comment by Blood-Asp** [comment]
What exactly are you trying here? All i see is that you make the math less accurate by dividing the integer first and cutting off decimals.

**Comment by Technus** [comment]
If u produce EU at rates near to Integer_max multiplying it first makes the integer overflow to negative values

**Comment by Technus** [comment]
Afaik it only occurs in large gens

**Comment by Blood-Asp** [comment]
then make it long instead of integer. but the way you change it here breaks calculation for small values.

**Comment by Technus** [comment]
can do

**Comment by Technus** [comment]
Done

**Comment by Bogdan-G** [comment]
idea: `Eff/10000` - hmm it is possible to replace the bit operation? (:P) I as that didnt notice these things especially

**Pull request merged**
