### PR TITLE
UBC Support / Ore System Restructure

### LINKED ISSUE #578: Scanning Forestry stuff (Bees, Saplings, etc...)
According to NEI scanning bees, and other forestry stuff it should consume 50mb of Honey. Reality is 100mb (which is correct, so the NEI shows the wrong number).

### PR DESCRIPTION
**Pull request by mura3277**
Added GT ores with UBC stone textures:
image
image

The goals of this were to add GT ore for UBC stones and also at the same time make it a lot easier to add more ores in the future. Now to add more ores, you just have to add a class that extends GT_Block_Ores_Abstract and have a similar structure to GT_Block_Ores, instantiate that class in Item_Block_And_Fluid loader and edit the setOreBlock method in GT_TileEntityOres.

Adding a Block parameter to the method getTexture in ITexturedTileEntity stops the "Texture sets" switching for all ore blocks when an ore block with a different "Texture set" is placed (@Blood-Asp You can ignore that PM on the IC2 forums).

Let me know if I've done anything incorrectly or inefficiently or if there is anything that should be changed about the ore system while I'm at it. This should also have a lot of testing with different existing and new worlds.

Extra Stuff:
- Fixed #578. Scanner now displays the correct mb of honey (Didn't think it was worth a separate PR)
- You can now specify a target biome name that mixes and small ores will only spawn in ("None" is every biome)
- Added Marble and Basalt world gen like the granites.
- Added missing materialicon textures for Lignite. (Didn't think it was worth a separate PR)
- Fixed an issue where Granite/Marble/Basalt didn't replace themselves, but continued to override the  metas of ores. This creates the situation in the below left image. With the fix in place, the last block to be placed in a given xyz takes dominance. Before(Left) and After(Right)
  image

Know Issues:
If a stone vein generates a stone block where an ore is, it correctly converts the ore to GT_Block_Ores1(If it isn't already), but seems to be failing to change the meta data of the tile in some situations. I'm still trying to figure out what is causing this issue.
image
Sometimes, the ore won't update properly, and if supplied with a block update it will get it's correct meta. I've see this behavior with the normal ores before, but I thought I'd mention it.
image

### CODE REVIEW

**Comment by mura3277** [comment]
So I think it would be best to have a few people test this out on existing large worlds to make sure everything this working properly. However everything seems to be working great from my testing and the only issues I've found are the two outlined in the main post.

**Comment by Blood-Asp** [comment]
Well, too much changed to just look at the code. A short check seems ok, will merge so others can help testing.

**Comment by mura3277** [comment]
@Blood-Asp btw, I don't think there us a built version of UBC that supports dev environments, so I'll pm you the jar I built on the ic2 forums.

Also, I just noticed this issue: http://i.imgur.com/2SO3wVw.gifv
The granite vein doesn't seem to of updated properly, but right clicking with a pick/breaking and relogging seems to update the blocks. I'm not sure if this was due to my changes?

**Comment by Bogdan-G** [comment]
> https://cloud.githubusercontent.com/assets/7321570/17046060/5f2c62d6-4fc7-11e6-96ac-1939393a23b3.png

this problem find(im look)(without UBC) in GT5 5.07.xx and before versions(?)

**Comment by draknyte1** [comment]
[23:32:29] <SomeGuyInTheRaisinFields> http://i.imgur.com/2SO3wVw.gifv
[23:32:53] <-> xbony2|afk is now known as xbony2|cube2
[23:33:14] <GregoriusTechneticies> lol
[23:33:24] <GregoriusTechneticies> that is called server lag
[23:33:28] <GregoriusTechneticies> + worldgen
[23:33:35] <SomeGuyInTheRaisinFields> He has to click them to change them
[23:33:52] <GregoriusTechneticies> yep
[23:33:58] <GregoriusTechneticies> serverlag + worldgen
[23:34:04] <GregoriusTechneticies> I'm serious
[23:34:13] <GregoriusTechneticies> its simple
[23:34:17] <SomeGuyInTheRaisinFields> Never seen it happen..
[23:34:29] <GregoriusTechneticies> for Worldgen modders use setBLock without updating the result to the client
[23:34:41] <GregoriusTechneticies> in order to not lag during generation
[23:34:56] <GregoriusTechneticies> since it is a shitload of setBlock Calls
[23:34:59] <bear989> i've seen it happen but never had to click it to get it to change
[23:35:15] <GregoriusTechneticies> it happens with every mod btw
[23:35:33] <SomeGuyInTheRaisinFields> So it's not actually a bug and we can just close the issue?
[23:35:45] <GregoriusTechneticies> yes

**Comment by draknyte1** [comment]
<SomeGuyInTheRaisinFields> http://i.imgur.com/2SO3wVw.gifv
<SomeGuyInTheRaisinFields> :p
<-> xbony2|afk is now known as xbony2|cube2
<GregoriusTechneticies> lol
<GregoriusTechneticies> that is called server lag
<GregoriusTechneticies> + worldgen
<SomeGuyInTheRaisinFields> He has to click them to change them
<GregoriusTechneticies> yep
<GregoriusTechneticies> serverlag + worldgen
<GregoriusTechneticies> I'm serious
<GregoriusTechneticies> its simple
<SomeGuyInTheRaisinFields> Never seen it happen..
<GregoriusTechneticies> for Worldgen modders use setBLock without updating the result to the client
<GregoriusTechneticies> in order to not lag during generation
<GregoriusTechneticies> since it is a shitload of setBlock Calls
<bear989> i've seen it happen but never had to click it to get it to change
<GregoriusTechneticies> it happens with every mod btw
<SomeGuyInTheRaisinFields> So it's not actually a bug and we can just close the issue?
<GregoriusTechneticies> yes

**Comment by draknyte1** [comment]
It's not related to your changes @Muramasa-, I indirectly asked Greg.

[SomeGuyInTheRaisinFields] http://i.imgur.com/2SO3wVw.gifv
[SomeGuyInTheRaisinFields] :p
[-] xbony2|afk is now known as xbony2|cube2
[GregoriusTechneticies] lol
[GregoriusTechneticies] that is called server lag
[GregoriusTechneticies] + worldgen
[SomeGuyInTheRaisinFields] He has to click them to change them
[GregoriusTechneticies] yep
[GregoriusTechneticies] serverlag + worldgen
[GregoriusTechneticies] I'm serious
[GregoriusTechneticies] its simple
[SomeGuyInTheRaisinFields] Never seen it happen..
[GregoriusTechneticies] for Worldgen modders use setBLock without updating the result to the client
[GregoriusTechneticies] in order to not lag during generation
[GregoriusTechneticies] since it is a shitload of setBlock Calls
[bear989] i've seen it happen but never had to click it to get it to change
[GregoriusTechneticies] it happens with every mod btw
[SomeGuyInTheRaisinFields] So it's not actually a bug and we can just close the issue?
[GregoriusTechneticies] yes

**Comment by Dream-Master** [comment]
Which version of UBC you are using in the libs folder. 
I get this crash all the time.
https://gist.github.com/Dream-Master/74873251aeded0bff14c88b5312e7f2d

**Comment by Dream-Master** [comment]
@Muramasa- 
What version of UBC you put in your libs folder?
I get the following crash:
https://gist.github.com/Dream-Master/803acf414af42c91e0f15d6809306ad7

**Comment by Dream-Master** [comment]
Nevermind I build me a dev version and all works fine.

**Comment by mura3277** [comment]
Thanks @draknyte1 for looking into that issue for me!

Also, if anyone needs a working build of UBC for dev environments (Sorry for the late reply @Dream-Master) PM me on the IC2 forums.

**Comment by Blood-Asp** [comment]
Best would be to upload the Dev version so some ddl page and add that Link to the Build Script. That would make it much easier for everyone.

**Comment by Blood-Asp** [comment]
Or maybe it is possible to fully remove UBC by calling the blocks from the Registry by name instead of linking to the mod files.

**Comment by mura3277** [comment]
I think the dependency on UBC is because I'm getting the textures of the blocks with GT_CopiedBlockTexture. I suppose we could add the textures manually and add it into the Textures class?

**Comment by Blood-Asp** [comment]
"Simply" Call the blocks from the Block Registry by its name. Look at GT_ModHandler.getModBlock for that.

**Pull request merged**
