### PR TITLE
Fix bug > Oil Teleportation to GC Planets #837

### PR DESCRIPTION
**Pull request by maixgame**
Fix bug extracting oil from the other world (Nether e.t.c.)

### CODE REVIEW

**Comment by leagris** [comment]
Hardcoded dimension 0 is an issue on servers with multiple overworld-like dimensions.

I'd suggest either:
- An allowed dimensions whitelist config as in [Galacticraft/core.conf](https://wiki.micdoodle8.com/wiki/Config#Settings_in_core.conf)
- Or check Biome from a whitelist/blacklist of Biome Type attributes or classnames (see a [typical Biome Data](https://docs.google.com/spreadsheets/d/1NryZ2jCRK2HmzcVPCpfSnFU1jKZ3qqJsuG-wPEbzwms/edit?usp=sharing))

Typically you would like to blacklist these Biomes:
```
net.minecraft.world.biome.BiomeGenHell
net.minecraft.world.biome.BiomeGenEnd
chylex.hee.world.biome.BiomeGenHardcoreEnd
thaumcraft.common.lib.world.biomes.BiomeGenEldritch
appeng.spatial.BiomeGenStorage
```

**Comment by maixgame** [comment]
This task is in the work, in any case, the oil swings from the overworld and this is a bug...

**Comment by draknyte1** [comment]
I suggest dimension black/whitelist, because biome generation isn't always correct. 

What worlds should and shouldn't have oil is a user choice. I'd personally leave it available on every dimension..

**Comment by maixgame** [comment]
these values still need to save, so... wait...

**Comment by leagris** [comment]
And Oil rig should pump Oil from the dimension it is deployed, but not pump overworld dimension 0 oil if it is placed for example in Twilight Forest.

**Comment by maixgame** [comment]
of course

**Comment by maixgame** [comment]
Is Working!

**Comment by maixgame** [comment]
More Update...

Add Underground Oil Generating settings in GregTech.cfg
Add supports White and Black List (DIM ID)
Add settings generating for standart Dimension and Galacticraft Dimension - Moon and Mars
Add settings for select type Underground Fluid - for Nether default Pahoehoe Lava, for Moon - Helium 3
Add settings max Amount Generating
For generating oil in other Dimension (Twilight Forest or Mystcraft) use settings - RealDimensionEnable

**Comment by draknyte1** [comment]
I like the idea of different fluids in different dimensions, but it should still be configurable. Personally, I'd like oil in whatever dimension I want, for example. 

How do other dimensions such as MorePlanets planets or RfTools work config wise?

**Comment by maixgame** [comment]
Yes, only Moon and Nether select type fluid -> **You can choose oil in config**. You can also set the maximum amount of liquid to the Moon, Nether and Overworld (MaxAmount Overworld include other world, for example Twilight Forest)
If you world don't generate Oil (for example Venus), add Dimension ID to White List

**Comment by maixgame** [comment]
Use [url](https://yadi.sk/d/a9lRu5af3DeKpf) for download this test build

**Comment by leagris** [comment]
I'd set moon fluid as Molten Cheese 😛

**Comment by maixgame** [comment]
OKAY

**Comment by Blood-Asp** [comment]
Are you now done with changes or still something WIP?

**Comment by maixgame** [comment]
still something WIP
I modify flexible options to Mrs. leagris (sorry) could pump Molten Cheese etc.

I'll write when I finish

**Comment by leagris** [comment]
Le 11/02/2017 à 03:22, maixgame a écrit :
> still something WIP
> I modify flexible options to Mr. leagris could pump Molten Cheese etc.
I meant having choice of fluid, helium3, molten cheese, cyprin, whatever
a modpack maker feels suit best.

Anyway, if your fix is good enough for a release, feel free to push the
fluid choice feature separately at a later stage and allow @Blood-ASP to
release a fixed build. Prioritize bug-fixes before new features.

-- 
Léa Gris

**Comment by maixgame** [comment]
`
    default {
        # Dimension ID or Class Name
        S:Dimension=Default

        gas_natural_gas {
            # Chance generating
            I:Chance=25

            # Max amount (Amount in step)
            I:MaxAmount=625

            # Min amount (Amount in step)
            I:MinAmount=0

            # Fluid registry
            S:Registry=gas_natural_gas
        }

        liquid_light_oil {
            # Chance generating
            I:Chance=25

            # Max amount (Amount in step)
            I:MaxAmount=625

            # Min amount (Amount in step)
            I:MinAmount=0

            # Fluid registry
            S:Registry=liquid_light_oil
        }

        oil {
            # Chance generating
            I:Chance=25

            # Max amount (Amount in step)
            I:MaxAmount=625

            # Min amount (Amount in step)
            I:MinAmount=0

            # Fluid registry
            S:Registry=oil
        }

        liquid_heavy_oil {
            # Chance generating
            I:Chance=25

            # Max amount (Amount in step)
            I:MaxAmount=625

            # Min amount (Amount in step)
            I:MinAmount=0

            # Fluid registry
            S:Registry=liquid_heavy_oil
        }

    }
`
I'm testing...

**Comment by maixgame** [comment]
your cheese)
`
   moon {
        # Dimension ID or Class Name
        S:Dimension=Moon

        molten-cheese {
            # Chance generating
            I:Chance=50

            # Max amount (Amount in step)
            I:MaxAmount=125

            # Min amount (Amount in step)
            I:MinAmount=0

            # Fluid registry
            S:Registry=molten.cheese
        }

        helium-3 {
            # Chance generating
            I:Chance=50

            # Max amount (Amount in step)
            I:MaxAmount=375

            # Min amount (Amount in step)
            I:MinAmount=0

            # Fluid registry
            S:Registry=helium-3
        }

    }
`

**Comment by draknyte1** [comment]
Looking good))
Let me know when it's ready to merge in mate.

**Comment by maixgame** [comment]
Okay, if current default setting not suitable for your development model, please correct in gregtech.api.objects.GT_UO_DimensionList.SetDafultValues();

**Comment by draknyte1** [comment]
What's the status on this one mate? Well tested? If not throw me a build and I'll have a mess around with it.

**Comment by maixgame** [comment]
Tested... and it works

**Comment by maixgame** [comment]
@Blood-Asp 
@draknyte1
I'm done with this PR

**Comment by draknyte1** [comment]
Can you build it for me to test?
I'll do the merge if I can't break it))

**Comment by maixgame** [comment]
@draknyte1 
https://yadi.sk/d/F9XWqJMp3DeCex

**Comment by draknyte1** [comment]
I have been testing this while developing this weekend, looks to be working correctly.
Unless I run into any issues or there's an objection from the others, I'll merge it in.

**Comment by Blood-Asp** [comment]
I'm the one to merge in...

I have currently a commit with almost 30 changed classes close to finish and have to check for collisions before any merge.

**Comment by draknyte1** [comment]
Don't just push commits when you're done, do it as you go so you actually look active...
On top of that, I've actually tested this. You can easily check for collisions, you don't need to manually review every aspect of it...

if you're REALLY wanting to check for merge conflicts, pull this repo, then -ff it to the same commit as master, git will list merge difs and conflicts...

**Pull request merged**
