### PR TITLE
Add usage for Tantalum №2

### PR DESCRIPTION
**Pull request by Spartak1997**
Add Tantalum foil special for SMD Capacitor recipes

### CODE REVIEW

**Review by draknyte1 — CHANGES_REQUESTED** [review]
doesn’t actually give any details what this does.

**Comment by Spartak1997** [comment]
This PR need for previous addition. Because in this thing I add ordict for Tantalum foil and plate special for recipes

**Comment by draknyte1** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/CONTRIBUTING.md
So make them one PR and close this..

**Comment by Blood-Asp** [comment]
i too would have preferred to have them in one PR, but not waiting for that...

**Pull request merged**
