### PR TITLE
ItemPipe tick time customization

### PR DESCRIPTION
**Pull request by Antifluxfield**
Fix bugs & tooptips

### CODE REVIEW

**Review by draknyte1 — CHANGES_REQUESTED** [review]
Dont change the constructor.. add a new one..
I dont see the point in this though?

**Comment by Antifluxfield** [comment]
Generally, nothing was changed, since we've never used the constructor with the time of ticking cycle as an argument. But if anyone use it, the tile won't be created as expected in the world.

**Comment by draknyte1** [comment]
I dont see why we ever would..
No harm done having extra flexibility though.

**Comment by Antifluxfield** [comment]
Also no idea why we have that constructor... But since it's already there, I think it would be better to fix it.

**Pull request closed without merging**
