### PR TITLE
Multi-lines tooltip support

### PR DESCRIPTION
**Pull request by Antifluxfield**
Use "/n " to seperate the tooltip to multiple lines.
Thanks @Exidex for your hint.

### CODE REVIEW

**Comment by Exidex** [comment]
I guess it makes more sense to use `\n` as separator

**Comment by Antifluxfield** [comment]
@Exidex Not a good idea. It will break the localization.

**Comment by Dragon2488** [comment]
/n will not break anything, but looks much more familiar

**Comment by Antifluxfield** [comment]
@Dragon2488 Sounds reasonable.

**Pull request merged**
