### PR TITLE
Fix for negative-coordinate vein generation, adjustments to recipes for stone dust, sand, and flint

### PR DESCRIPTION
**Pull request by MauveCloud**
Addresses #718 and #705

Vein centers will now be at roughly ... -120, -72, -24, 24, 72, 120, ... on the x and z coordinates instead of ... -104, -56, -8, 24, 72, 120, ...

Pulverizing furnaces or cobblestone will now produce stone dust (for consistency, similar to cobblestone slabs, or droppers/dispensers made mostly from cobblestone), and so will pulverizing gravel.  However, gravel can be sifted (with a scoop in early game, or with the electric machine later) to get flint, or hammered to get sand.

### CODE REVIEW

**Comment by codewarrior0** [comment]
> hammered to get sand.

Do you happen to know if this will allow the JackHammer (HV) to break Gravel now? Or is it just a crafting recipe with the Hammer?

**Comment by Dragon2488** [comment]
Blood has already said that furnace to sand recipe is correct and shouldnt be changed.

**Comment by MauveCloud** [comment]
> Do you happen to know if this will allow the JackHammer (HV) to break Gravel now? Or is it just a crafting recipe with the Hammer?

I haven't checked that yet.  Having the Forge Hammer recipe allows a regular hammer tool to break gravel into sand (even if such a recipe was added by Minetweaker), dunno about the JackHammer.

Edit: the JackHammer does not break gravel.  If you want me to add that, please provide justification.

> Blood has already said that furnace to sand recipe is correct and shouldnt be changed. 

Not exactly.  What he said in the bug was "I somehow want to keep the furnace = 6 sand recipe... always used it for mass sand production."  That isn't a claim that the recipe is correct, or a justification for the inconsistency, and the Forge Hammer recipe provides an alternative for mass sand production from cobblestone.

**Review by Timeslice42 — COMMENTED** [review]
You have some whitespace inconsistancies in several places.

**Comment by MauveCloud** [comment]
> You have some whitespace inconsistancies in several places.

I think that's an artifact of my editor settings - I hadn't noticed that it was adding tabs instead of spaces, which GitHub expands to width 8 instead of 4.  I'll see if I can fix that.

**Comment by Blood-Asp** [comment]
Now conflics with previous PR...

**Pull request merged**
