### PR TITLE
Config for using only soldering alloy

### PR DESCRIPTION
**Pull request by Techlone**
This changed check gets a config value by name `recipes.harderrecipes.useonlygoodsolderingmaterials` and doesn't add recipes with tin and lead if this cfg value true. I think it's useful. Default it's `false` and doesn't change recipes.

### CODE REVIEW

**Comment by Techlone** [comment]
Don't pay attentions on merge commits

**Comment by Techlone** [comment]
Hm, recipes of adv circuit still use tin and lead. Don't merge the PR now please.

**Comment by Techlone** [comment]
Done

**Comment by leagris** [comment]
An other option is to add lead-free soldering alloy that fail after some time :rofl:

**Pull request merged**
