### PR TITLE
Correct description of regulator

### PR DESCRIPTION
**Pull request by Antifluxfield**
Correct description of regulator.
The cost is actually tripled at:
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_Regulator.java#L95

### CODE REVIEW

**Comment by Antifluxfield** [comment]
Rebalance the cumene recipe.

**Comment by draknyte1** [comment]
Please try keep each change to seperate pull requests. Makes revision/reviewing easier.

**Comment by Antifluxfield** [comment]
OK...

**Review by draknyte1 — CHANGES_REQUESTED** [review]
So, is it meant to use 1eu or 3eu?
Might be better to fix EU usage rather than the description. Just depends what is actually intended I guess.

**Comment by Antifluxfield** [comment]
@draknyte1
Well, I have reviewed the code of GT5.07.07, it shows that the regulator consumes 3EU per item since that time. Besides, the regulator is more powerful and more convienient than any other automation devices, so it's reasonable for it to consume more energy. Thus I think the 3EU-cost should be intended, so I changed the description instead of the EU usage.

**Comment by SapientMC** [comment]
@Antifluxfield Could you please also improve Pump (block) tooltips? I think info about its pump area should be added. Numbers are here https://ftb.gamepedia.com/Pump_(GregTech_5_Unofficial)

**Comment by mura3277** [comment]
@SapientMC Added by 9fc5d17

**Review by draknyte1 — APPROVED** [review]

**Pull request merged**
