### PR TITLE
Fix maintenance cover

### PR DESCRIPTION
**Pull request by UhoMazino**
Fix bug in maintenance cover logic when its try calculate turbine rotor needed maintenance by wrong and unpredicted ways.

### CODE REVIEW

**Review by draknyte1 — CHANGES_REQUESTED** [review]
This change would break my GT++ Turbines which don't extend `GT_MetaTileEntity_LargeTurbine`.

There is no reason to make this cover strictly for Large Turbines either.. Other Multis exist which use the GUI slot.

**Comment by NNM42** [comment]
what it mean "my gt++ turbines"?

**Comment by SapientMC** [comment]
@draknyte1 Is it really the GT that must remain compatible with all the addons to it, and not vice versa?

**Comment by draknyte1** [comment]
@Sapientmc, In this case, yes. 

You're turning compatibility with all mods to only supporting the GT turbine. Nothing mods can do to add support into the cover, so compatibility remains on GT.

**Comment by SapientMC** [comment]
@draknyte1 but only GT turbine has rotors that takes damage and should be replaced on last points of durability.

**Comment by mitchej123** [comment]
Make it work with both.  Previous behavior if not turbine and this behavior if it is a turbine

**Comment by draknyte1** [comment]
There's no need to hard instance it as a GT turbine though, which is my point. Because the new field isn't necessary either..

Which means that my turbines are supported still...

**Comment by NNM42** [comment]
@draknyte1, yep this is your point.
https://imgur.com/ECwyOdb

**Comment by draknyte1** [comment]
@NMM42, either make the changes I've requested or I'll just close your PR. Take your smartass attitude elsewhere, because nobody else will approve it. 🤔

**Pull request merged**
