### PR TITLE
Fixed #1000.

### LINKED ISSUE #1000: [5.09.29] Crash while MC loading
gregtech-5.09.29pre2.jar works fine
gregtech-5.09.29.jar - crashes
https://pastebin.com/j0L5iWzP

### PR DESCRIPTION
**Pull request by Dimach**
Yep, i used deprecated api, but it supported in java7.

### CODE REVIEW

**Comment by draknyte1** [comment]
Please ensure it works with latest J8. 8 support is far more important than 7, why people would even still use 7 is beyond me..

**Comment by draknyte1** [comment]
April Fools is also April 1st, not month three. Unless the older API has January at 0..

**Comment by Blood-Asp** [comment]
Yes, the older one has january at 0. Tried that one before myself but exactly because of that depricated i changed that. 
But adding a try/catch because of that depricated would maybe be a good idea. since it is posible to be removed in some future java version and whould then crash again.

**Comment by Dragon2488** [comment]
Fuck, please don't do shit. It can be easily replaced with new Calendar API.

**Comment by Dragon2488** [comment]
Fixed it myself, maybe getBoolean shouldn't be there. But fuck, code properly or don't code at all.

**Comment by draknyte1** [comment]
Supporting J7 imho is stupid when it's so outdated. The fix is update Java, not support old Java.

**Comment by Bogdan-G** [comment]
^ J8 no need, no perfomance, new bugs and etc :D 
PS goto J9 xD

**Comment by MauveCloud** [comment]
> PS goto J9 xD

That's difficult to agree with when Java 9 is still in "Early Access" stage (and from what I can find, the latest estimate for an official release is July 2017)

**Comment by draknyte1** [comment]
J7, still has outstanding issues that will never be fixed. API components 8 replaced are faster, including the entire JS engine. Supporting deprecated API doesn't really benefit anyone when J8 is the standard, even for EE.

**Comment by Bogdan-G** [comment]
>EE

J2EE or mod EE?
PS (for everyone) about the pull-request: why create a object calendar? There is an variant without dependency API.

**Pull request closed without merging**
