### PR TITLE
AdvMinerII: check that ore block still exists; consider chance output

### PR DESCRIPTION
**Pull request by Techlone**

### CODE REVIEW

**Comment by ShelfOwl** [comment]
I heard the Adv.Miner2 has ability to produce subproducts by 100% chance is intended behavior,
differ to actual behavior a bit, though.
See also: #381

@Blood-Asp do you reconsider it? There are 3 calculations at all.
1. 1-4x 2 Crushed + 1-4x 1 subproduct : actual behavior in GT 5.09.21 or below
2. 1-5x 2 Crushed + 1x   1 subproduct : @Blood-Asp mentioned in #381
3. 1-4x 2 Crushed + 1-4x 1x10% chance to subproduct: this PR I assume (hence it seems 90% chance to produce 1 subproduct)

**Comment by Techlone** [comment]
I think that config parameters is the best solution for this issue.
I'm one of authors of IIA modpack. Our community (and we are too) consider that AdvMinerII should take into account chances of byproducts. Are you think differently? See my first sentence.

**Comment by Blood-Asp** [comment]
The main reason i did not add a chance to the byproduct was lazyness... I do not really care about that point.

**Comment by ShelfOwl** [comment]
For me Adv.Miner2 is just an alternative to exploring veins, is not hard in EV+ age.
So I do not care how effecient it will be. Config is good idea.

**Pull request merged**
