### PR TITLE
BoP Nether fix

### PR DESCRIPTION
**Pull request by MauveCloud**

### CODE REVIEW

**Comment by Blood-Asp** [comment]
Seeing how much fixes you commit, want to be added as Collaborator?

**Comment by Blood-Asp** [comment]
But best for this commit would be to keep old behavior. aka: Only End or Nether to as dimension 1 or -1, every other as 0 spawning same as overworld.

**Comment by MauveCloud** [comment]
> But best for this commit would be to keep old behavior. aka: Only End or Nether to as dimension 1 or -1, every other as 0 spawning same as overworld.

Except that's not really what the old behavior was doing.  Only _vanilla_ End or Nether was being treated as dimension 1 or -1 respectively.  BoP End and Nether were inheriting overworld spawn type, and so were Galacticraft planets and asteroids, despite the WorldGeneration file having separate entries for them in each small ore type and mix vein.

**Comment by Blood-Asp** [comment]
Well, to rephase it, every dimension not handled differently should behave as 0/overworld. Other dimensions should, if possible, have by default GT overworld oregen. For example Twilight Forest or Deep Dark. Suddenly not spawning GT ores there will annoy most people more than not having correct ores in BoP Nether.

**Comment by MauveCloud** [comment]
Okay.  How's this?

**Comment by Blood-Asp** [comment]
That should be fine.

**Pull request merged**
