### PR TITLE
Improved output bus handling

### PR DESCRIPTION
**Pull request by MauveCloud**
Should address bug #180 (Output busses are not "smart")

### CODE REVIEW

**Comment by MauveCloud** [comment]
The change to GT_Block_Reinforced.java should fix #439, as well as change the preferred tool to a shovel instead of an axe.

**Comment by Blood-Asp** [comment]
Does it also help with not working in advanture mode?
Also i would prefer to stay with an axe. More intuitive.

**Comment by MauveCloud** [comment]
How is an axe intuitive?  As mentioned in the bug, other mods that add charcoal pits use shovels.  It doesn't help with not working in adventure mode.

**Comment by Blood-Asp** [comment]
Shovel in TFC or what other charcoal pit? For me personally i would only think of trying axe or pickaxe to break in coal transformed wood blocks.

**Comment by MauveCloud** [comment]
I don't know what other mods add charcoal pits/piles, but Timeslice42 said that real-life charcoal piles also involve using a shovel to get the charcoal when it's done, and the picture "Opening of the charcoal pile" at https://en.wikipedia.org/wiki/Charcoal_pile seems to support that (I admit I don't have personal experience with charcoal piles in real life).

Edit: I found a couple of YouTube videos demonstrating how to make charcoal with a charcoal pile.  One video had a guy just using his bare hands, another had a group using rakes and shovels.

**Comment by Timeslice42** [comment]
You are now my #1 person of the month, Mauve. Thanks for both of these :)
I knew fixing the output bus wouldn't be as hard as Blood thought...

**Pull request merged**
