### PR TITLE
Heat Exchanger updates

### PR DESCRIPTION
**Pull request by pyure**
* Can now adjust the minimum threshold for Superheated steam via Integrated Circuits inside the LHE

* Restored full useWater reliance
* HotCoolant now increases efficiency at same rate as lava (80 instead of 20, feel free to revert)
* Please double-check math on Lava output.

### CODE REVIEW

**Comment by pyure** [comment]
ref #141

**Comment by Blood-Asp** [comment]
Do you take care of changing the informations on the wiki?

**Comment by pyure** [comment]
I certainly will when you're ready.  I'm still releasing these pull requests a bit blind, I can't get my end to compile.

**Comment by Blood-Asp** [comment]
Just released the new version half an hour ago.
I did no testing with our last two pull requests, only checked the code a bit.
On you turbine changes i did test most functions.

I also @Dream-Master seems to have the same problem you have with compiling. So maybe it is something both of you do and i can't figure it out.

**Comment by pyure** [comment]
I'll test your version, thanks kindly.

I've updated the wiki for the LHE.
http://ftb.gamepedia.com/Large_Heat_Exchanger#Math

**Comment by Dream-Master** [comment]
I get a pm back from Greg with a maybe solution. I will test it first .

**Comment by Dream-Master** [comment]
IDEA solution:

change this line from 
````````````````````````````
for (IMetaTileEntityItemPipe tTileEntity : GT_Utility.sortMapByValuesAcending(IMetaTileEntityItemPipe.Util.scanPipes((IMetaTileEntityItemPipe)tMetaTileEntity, new HashMap(), 0L, false, true)).keySet())
``````````````````````````
``````````````````````
for (IMetaTileEntityItemPipe tTileEntity : GT_Utility.sortMapByValuesAcending(IMetaTileEntityItemPipe.Util.scanPipes((IMetaTileEntityItemPipe)tMetaTileEntity, new HashMap(), 0L, false, true)).keySet())`
``````````````````````````````

replace thr
``````````````
tTileEntity 
`````````````````
 in this file to this:

````````````````````
((IMetaTileEntityItemPipe)tTileEntity)
``````````````````````````````

**Comment by Dream-Master** [comment]
Whole file:

````````````````````````````
package gregtech.common.items.behaviors;

import gregtech.api.GregTech_API;
import gregtech.api.interfaces.metatileentity.IMetaTileEntity;
import gregtech.api.interfaces.metatileentity.IMetaTileEntityItemPipe;
import gregtech.api.interfaces.metatileentity.IMetaTileEntityItemPipe.Util;
import gregtech.api.interfaces.tileentity.IGregTechTileEntity;
import gregtech.api.items.GT_MetaBase_Item;
import gregtech.api.items.GT_MetaGenerated_Tool;
import gregtech.api.util.GT_LanguageManager;
import gregtech.api.util.GT_Utility;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import net.minecraft.entity.item.EntityItem;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.entity.player.PlayerCapabilities;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.world.World;

public class Behaviour_Plunger_Item
  extends Behaviour_None
{
  private final int mCosts;
  
  public Behaviour_Plunger_Item(int aCosts)
  {
    this.mCosts = aCosts;
  }
  
  public boolean onItemUseFirst(GT_MetaBase_Item aItem, ItemStack aStack, EntityPlayer aPlayer, World aWorld, int aX, int aY, int aZ, int aSide, float hitX, float hitY, float hitZ)
  {
    if (aWorld.isRemote) {
      return false;
    }
    TileEntity aTileEntity = aWorld.getTileEntity(aX, aY, aZ);
    if ((aTileEntity instanceof IGregTechTileEntity))
    {
      IMetaTileEntity tMetaTileEntity = ((IGregTechTileEntity)aTileEntity).getMetaTileEntity();
      if ((tMetaTileEntity instanceof IMetaTileEntityItemPipe)) {
        for (Object tTileEntity : GT_Utility.sortMapByValuesAcending(IMetaTileEntityItemPipe.Util.scanPipes((IMetaTileEntityItemPipe)tMetaTileEntity, new HashMap(), 0L, false, true)).keySet())

        {
          int i = 0;
          for (int j = ((IMetaTileEntityItemPipe)tTileEntity).getSizeInventory(); i < j; i++) {
            if (((IMetaTileEntityItemPipe)tTileEntity).isValidSlot(i)) {
              if ((((IMetaTileEntityItemPipe)tTileEntity).getStackInSlot(i) != null) && (
                (aPlayer.capabilities.isCreativeMode) || (((GT_MetaGenerated_Tool)aItem).doDamage(aStack, this.mCosts))))
              {
                ItemStack tStack = ((IMetaTileEntityItemPipe)tTileEntity).decrStackSize(i, 64);
                if (tStack != null)
                {
                  EntityItem tEntity = new EntityItem(aWorld, ((IGregTechTileEntity)aTileEntity).getOffsetX((byte)aSide, 1) + 0.5D, ((IGregTechTileEntity)aTileEntity).getOffsetY((byte)aSide, 1) + 0.5D, ((IGregTechTileEntity)aTileEntity).getOffsetZ((byte)aSide, 1) + 0.5D, tStack);
                  tEntity.motionX = 0.0D;tEntity.motionY = 0.0D;tEntity.motionZ = 0.0D;
                  aWorld.spawnEntityInWorld(tEntity);
                  GT_Utility.sendSoundToPlayers(aWorld, (String)GregTech_API.sSoundList.get(Integer.valueOf(101)), 1.0F, -1.0F, aX, aY, aZ);
                }
                return true;
              }
            }
          }
        }
      }
    }
    return false;
  }
  
  private final String mTooltip = GT_LanguageManager.addStringLocalization("gt.behaviour.plunger.item", "Clears Items from Pipes");
  
  public List<String> getAdditionalToolTips(GT_MetaBase_Item aItem, List<String> aList, ItemStack aStack)
  {
    aList.add(this.mTooltip);
    return aList;
  }
}
````````````````````````````````````

**Comment by pyure** [comment]
Thanks DM, I'll try that this week.

**Pull request merged**
