### PR TITLE
Deprecate the old materials that were removed

### PR DESCRIPTION
**Pull request by YoungGT**
Deprecate the old materials that were removed, shouldn't break mods using these materials.
And the name of tricalcium phosphate is the same as phosphorus's, so I add "NEW" to phosphorus to distinguish them.

### CODE REVIEW

**Comment by Blood-Asp** [comment]
Thats the wrong way to fix it. 
As example for deprication look here: https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/enums/Materials.java#L758

**Comment by Blood-Asp** [comment]
Also pull the main repo changes. otherwise i have to resolve merge conflicts.

**Comment by YoungGT** [comment]
well too late for me....

**Comment by Blood-Asp** [comment]
Did it myself to get an end to this: https://github.com/Blood-Asp/GT5-Unofficial/commit/88a7715fcaa8417f15713175de3b5f5a45f65266

**Pull request closed without merging**
