### PR TITLE
Fixed #1406

### LINKED ISSUE #1406: Bug with pipes 32pre2
This is how old versions of the pipe work. Machines accept steam from either side.
https://i.imgur.com/mclZreE.png

Pipes in 32pre3. The steam is not in the oven. But in the tube there is. In the oven there is an object for frying ..
https://i.imgur.com/FtjcQ9S.png

The steam left the boiler in the first block of the pipe. In the second block of the pipe is not.
https://i.imgur.com/3DyVh08.png
https://i.imgur.com/5smcOSk.png

### PR DESCRIPTION
**Pull request by Dimach**

### CODE REVIEW

**Review by draknyte1 — APPROVED** [review]

**Comment by draknyte1** [comment]
Can you please write a description next time? 
I don't care if it's a single line PR that is obvious, I set guidelines and expect people to follow them.

**Comment by Dream-Master** [comment]
@draknyte1 is this important for GTNH too?

**Comment by draknyte1** [comment]
@dream-master your best bet would be to ask whoever has managed the pipe fixes in your fork so far. But I'd assume you'd want it merged if it's applicable.

**Comment by SapientMC** [comment]
@draknyte1 It's the fix for error in this PR https://github.com/Blood-Asp/GT5-Unofficial/pull/1378

**Comment by draknyte1** [comment]
I'm aware what it is. But there's PR guidelines for a reason.. so we don't have to read the code to know what the fuck things do.. 

I want to read code to review it, not to understand what you're trying to PR..

**Comment by SapientMC** [comment]
@draknyte1 PR #1378 fixed bug with fluid distribution to more than 3 different ways. And added new fluid distribution mechanics: larger pipe gets more.
But added 2 new bugs.
1. In some cases fluid do not go into one of pipe at the fork at all.
2. Steam does not loads to machine from top side.

This PR fixes both of them and simplifies fluid distribution: equally to all consumers.

**Pull request merged**
