### PR TITLE
New Heating coils.

### PR DESCRIPTION
**Pull request by OneEyeMaker**
//Second attempt.
I added two tiers of heating coils for multiblock machines (such as Blast Furnace and Multi-Smelter) to process end-game (IV+) materials.
Also I changed stats of some materials to _"bind"_ them to specific tiers (to add some _challenge_ to IV+ era of game).
@Blood-Asp 
I want to continue work on this project.
If you like this idea, please, say, should I redefine (_"re-bind"_) another materials (to fill IV+ tiers with more content).
Maybe, it would be nice (and I want to do that) to move all coil blocks to another Block (BlockCasings5). _And I know, that it breaks compatibility._
Also I want change achievements system (only for end-game), because now it designed only for LV-IV tiers (not for LV-UV/MAX tiers).
What do you think about all that? Do you have any ideas? _I want to know your vision._

### CODE REVIEW

**Comment by Blood-Asp** [comment]
I did not have the time to check your changes yesterday and currently i'm only online with my mobile, so also not good to look at it.

Basicly your ideas Sound fine so keepnworking. ;)

More LuV+ Content Sounds good, but for moving old stuff around best send me an easy list first so I can check it before you make all the work.

Moving Coils to a new block should be fine as long you give the old Coils an disabled texture and an crafting recipe to convert them.

What do you mean with achievement System changes? Simply new IV+ ones, or reworking existing stuff?

I personally will not do that much anymore with GT5. Finish pollution, the armor, some circuitchanges changes and finally add the lightning rod.

After that I will try a plain port to 1.10 but not sure if I can handle the rendering code changes.

**Comment by OneEyeMaker** [comment]
@Blood-Asp 
Ok, I understood you.
My idea is very simple: add more end-game (IV+) content. For now I want to add coils for EBF.
Now GT has:
- Cupronickel coils for MV+ era;
- Kanthal coils for HV+ (Kanthal requires Vacuum Freezer, Vacuum Freezer requires HV circuitry).
- Nichrome coils for HV/EV+.

My small project:
- Tungstensteel coils for IV+ era;
- ??? for LuV+ (Maybe, something like Nb-Ti/V-Ga. What do you think about it?).
- Naquadah Alloy for ZPMV+ (Maybe, I should move this material to UV...)
- ??? for UV (I haven't any ideas for last coils. But it should be very strong to allow produce Naquadria for Neutronium reaction).

Also, I want to change properties of some materials according with these changes:
- All Naquadah related materials shold require LuV/ZPMV+ temperatures to make. (_Cosmic_ technologies should have _cosmic_ price/cost to obtain it :))
- Also, all HSS-? materials should require IV+ temperatures, because components from these materials are used to create IV+ machines.
- And, maybe, some materials for superconductor can be made only in EBF with IV+ coils (V-Ga/Nb-Ti).

And, finally, I want to add more achievements for end-game (now GT's achievements cover only LV-IV tiers).

@Blood-Asp 
To finish this work I need some advices from you (how to choose materials and don't break balance and don't make GT _non-realistic/magical_ mod **at all**).

P. S. Sorry for my English, I'm from Russia.

**Comment by OneEyeMaker** [comment]
Now I moved all heating coils to BlockCasings5. For compatibility with previous versions I leave _overheated_ (read: _deprecated_) versions of Cupronickel, Kanthal and Nichrome coils. (I tested backward compatibility with current version of GT - it works: after starting old world with newest features, all textures of coils transfrom into pale ones; multiblock becomes inactive; and player just need to break coils with wrench and craft them into new ones.)
For now I added only Tungstensteel (IV tier) and Naquadah Alloy coils (ZPMV/UV tier). I want to add more (for each tier). But (as I said in previous post) I need some help/advice with selection of materials.

**Comment by OneEyeMaker** [comment]
Summary for now:
- Old heating coils moved to another block (old ones I made "overheated").
- Added 4 new heating coils (for IV-UV tiers, not sure about materials, but it's simple to change).
- Found one weird thing in recipes: all LV-EV components require wires/cables, which can transfer corresponding voltage (LV-EV); but all IV-UV components require cables with lower tier (EV-ZPMV). I changed this - now all components require cables of the same tier.
- Changed properties of some materials (to "bind" these materials for specific tiers).

@Blood-Asp 
I know, that you're busy and have little time to work with this mod (especially with code of PRs).
But if you like _**this idea**_, let me know. (Should I continue work and finish this small project?)

**Comment by draknyte1** [comment]
Keep in mind making changes to the casing blocks effects other mods which rely on them. I'm striving to maintain 100% compat between 5.08, 5.09 and my own Fork of GT which sits somewhere in the middle.

@OneEyeMaker, we should have a chat sometime, let me know your best way of contact.

**Comment by OneEyeMaker** [comment]
@draknyte1 
https://discord.gg/ac9mB

**Comment by Blood-Asp** [comment]
Looking trough the code, i looks mostly ok. I need some more ingame test to be perfectly sure, but that should be done soon.

There is only one think i would like to have changed.
The "overheated" coils is a bad idea. That is not a game element of GT, but purely deprecation because of code changes. So they should be "deprecated", have a clearly broken texture(best the default texture missing icon of mc) and fix should be done by simply crafting. Vacuum Freezer is not even working for all players, because those that just reached the EBF and only have cupronickel coils do not have an vacfreezer.

**Comment by draknyte1** [comment]
I wouldn't use the Purple/Black texture.. just use the ! casing texture. 
Deprecated != broken. Don't make it look like it or people will think it is.

**Comment by Dream-Master** [comment]
Vac freezer was my idea because In the first place I thought coils can overheated in the burning process so only a misunderstanding of the name. Put the old blocks in crafting grid would be ok and rename the blocks to deprecate maybe enough. I don't like the idea using the "no texture" icon because looks so ugly.

**Comment by Blood-Asp** [comment]
Only renaming the blocks to deprecated is not enough. I can Garantie that many players will complain about the EBF not working because they can not read. The issue must be visible directly.

**Comment by Dream-Master** [comment]
mh maybe you right. The No Texture Blocks maybe the best solution.

**Comment by OneEyeMaker** [comment]
@Blood-Asp 
Deprecation should be visible: 
- I changed name of blocks;
- I changed tooltip of deprecated casings;
- I changed texture to RENDERING_ERROR (purple-black texture). => It's visible in world, that blocks are "broken". (Should I add purple-black texture with "Replace me!" text overlay?)
- I changed code in MetaTileEntities of controllers => It is visible in GUI, that machine can't work with old coils. (Or should I add specific line to GUI of controllers, something like "Broken coils" before line "Incompatible structure"?)

I think this is enough. If you don't think so, please say me, what can I do. 

P. S. Sorry for my English.

**Comment by Blood-Asp** [comment]
The current changes should be enough. Will merge once i'm home.

**Comment by leagris** [comment]
Le 26/07/2016 à 07:44, Martin a écrit :

> Vac freezer was my idea because In the first place I thought coils can
> overheated in the burning process so only a misunderstanding of the
> name. Put the old blocks in crafting grid would be ok and rename the
> blocks to deprecate maybe enough. I don't like the idea using the "no
> texture" icon because looks so ugly.

Maybe you could simply replace the blocks during `checkMachine` and
don't bother players with the 'Oh What The...'

## 

Léa Gris

**Pull request merged**
