### PR TITLE
Turbine rebalance

### PR DESCRIPTION
**Pull request by mura3277**
Added the Diesel Generator
Added 3 new turbine casings
Changed the different turbine multi blocks to require tiered casings:
Steam = Turbine Casing
HP Steam = Stainless Steel Turbine Casing
Gas = Stainless Steel Turbine Casing
Diesel = Titanium Turbine Casing
Plasma = Tungstensteel Turbine Casing

A couple things to highlight:
This is my first time tinkering with GT multiblock code so it's quite possible I have overlooked/missed something but it seems to be working fine. I really did think that the better turbines were too easy to make, especially the plasma turbine. I hope you agree with my changes.

For the Diesel Generator, all I did was copy and Plasma Generator class and instead of having optimal flow \* 40 it's \* 5. In my opinion, the Diesel Generator should be the 2nd best Large Turbine so I thought it was an acceptable amount of energy production. Feel free to make changes.

Let me know if there is anything I'm missing or need to fix.

Issues I know of:
I couldn't figure out how to get the input hatch, maintenance hatch and dynamo to match the casing texture.

### CODE REVIEW

**Comment by MauveCloud** [comment]
I like the idea of having a multiblock diesel generator, but I'm not sure it makes sense for it to be so similar to the other large turbines, since that presumably means it will require a metatool turbine item in the interface.  IRL, from what I can find about diesel engines, they require high compression in pistons, and probably wouldn't work as turbines (technically, I found a YouTube video that claimed to be of a diesel turbine, but it looked like it required constant tweaking and didn't seem very practical).  Also, the single-block diesel generators in GT use electric pistons and gears in the recipes, rather than rotors like the single-block steam and gas turbines.

**Comment by leagris** [comment]
@MauveCloud Diesel Turbine generators accept a variety of fuels and are a real thing in use within industrial facilities or in data centers. These are also used in large diesel electric vehicles: (M1 Abraham Tank, Locomotives).
These accept a variety of fuels including gas.

@Muramasa- I really think you should have added diesel generator fuels to the existing Gas turbines instead of adding a distinct type of multi-block. Gas and Diesel turbines are the very same thing.

**Comment by MauveCloud** [comment]
@leagris sorry, I'd forgotten that the M1 Abrams engine was actually a turbine.  However, the fuels listed for it are all in liquid phase at room temperature and standard pressure afaik, so I'm not so sure a diesel turbine is really the same as a gas turbine (which takes fuels that are already in gas phase at room temperature, like methane and hydrogen)

**Comment by Blood-Asp** [comment]
As almost all huge generators for emergency power or huge vehicles i know of use piston engines, so i took some time to look at wikipedia why that is so. It seems also most huge fuel based power plants i could find use the fuel to heat water for steam turbines.

As far i could see it, the reason for that is that turbines are better fit for light fuels and gasses, while the efficiency of them goes far down the more heavy the fuel is.
For example the mentioned Abrams turbine engine: It is quite compact and has a good power curve, but the fuel efficiency of it is really bad. About half the efficiency of other tanks with the same engine power. Also the high rotation speed makes complex gears nessary.
So a fuel turbine for power generation seems to be a bad idea. 

So back to the PR: The changes&additions are quite big, so it will take some time to look trough it.

**Comment by leagris** [comment]
@Blood-Asp Good point about efficiency. Though, pushing further this reasoning, it also question the pertinence of Plasma turbines as already mentioned here: https://github.com/Blood-Asp/GT5-Unofficial/issues/162

**Comment by mura3277** [comment]
I appreciate everyone's feedback on this pull request!

So to explain a couple things, the reason I wanted a diesel turbine is because I really really liked all of the development into Oil/Fuel, but felt like there wasn't a great way to produce power from it other than the single block generators. I did think about adding them to the Gas Turbine @leagris, however the effort put into producing enough fuel wasn't really going to be worth the energy output. I do really feel like the refined fuel category should really generate more power than the others except for Plasma of course.

Making the turbines have tiered casings was because it really was not difficult at all to go from a Steam Turbine to a Plasma Turbine as it just required the main block to be made. I feel like this change balances the turbines a little more, but of course everybody is welcome to offer their input.

@MauveCloud, I agree that it would be more interesting to have a different multiblock to generate power from refined fuels, but that's not really something I could personally do and would come down to BloodAsp, but since he already has  a lot to do, my thoughts were this was the next best thing.

@Blood-Asp, Keep in mind most of the 117 file changes are textures for the different turbine casings.

**Comment by mura3277** [comment]
So I have been messing around with creating a new multiblock for a Diesel Engine and it's going well.

What I'll do is close this PR and submit one that just has the turbine casing changes, then submit the diesel engine in a new PR.

**Pull request closed without merging**
