### PR TITLE
Fix Super fuel recipes

### PR DESCRIPTION
**Pull request by Techlone**
#540

### CODE REVIEW

**Comment by Blood-Asp** [comment]
The diff is a bit difficult to read because of the formatting changes, but if i understand it right, you changed "tile.railcraft.cube" into "cube"? That does not fix the issue.

**Comment by Blood-Asp** [comment]
Fixed it myself https://github.com/Blood-Asp/GT5-Unofficial/commit/e21311b919d8f7f2e6ac15afda1b083179684f61 by calling the coke block directly from the railcraft code: "EnumCube.COKE_BLOCK.getItem()". Now whatevery namechange happens to that block will not break the recipe. I still wonder why railcraft uses close to no oredicts.

**Comment by Techlone** [comment]
> That does not fix the issue.

Strange... I tested it with and without Raicraft and Thaumcraft before PR and all work fine.

Also "cube" is used in pyrolyse oven's recipes [this](https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L1287).

**Comment by Techlone** [comment]
> I still wonder why railcraft uses close to no oredicts

Are you saw how to realize RC's trails? A pell-mell of metadata and NBT. It was the hell to me when I wrote scripts for them :)

**Comment by Blood-Asp** [comment]
I should fix the pyrooven recipe too. At last there the recipe will simply be removed when failing and not remain half broken.

**Pull request closed without merging**
