### PR TITLE
Patched ME energy tunnel, now they can emit GT energy.

### PR DESCRIPTION
**Pull request by Dimach**
Patch loads only when AE installed.

### CODE REVIEW

**Comment by SapientMC** [comment]
@Dimach Всего изящества твоего варианта оценить не могу, но судя по тому, что там всего около 100 срок кода, то это очень круто :)

**Comment by danbka33** [comment]
It's broken.
> java.lang.IllegalAccessError: tried to access field appeng.parts.p2p.PartP2PIC2Power.OutputEnergyA from class appeng.parts.p2p.PartP2PGTPower
	at appeng.parts.p2p.PartP2PGTPower.outputEnergy(PartP2PGTPower.java:57)
	at appeng.parts.p2p.PartP2PGTPower.tickingRequest(PartP2PGTPower.java:84)
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:92)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
	at appeng.me.Grid.update(Grid.java:216)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:239)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_138_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:46)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:116)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:227)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:710)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Blood-Asp** [comment]
Comes that error only from too high security settings of the JVM or is that an general issue? Or maybe it only works with certain AE2 versions? Well, generally i think this looks quite unstable to me but i do not know enough about reflection and stuff to be sure it this is safe or not...

**Comment by Dimach** [comment]
This exception produces by code that not using reflection. I rewrite it to make code more safe. In any case, try/catch can handle almost all exceptions, if they will produce, tunnel will work as before the patch.

**Pull request merged**
