### PR TITLE
Cable fix pr

### PR DESCRIPTION
**Pull request by AndreySolodovnikov**
this PR includes:
1.Small fix for OR, added a gui(sorry I've forgotten to add it in previous PR)
2.Fix for low performance when IC2SourcesCompat is enabled

### CODE REVIEW

**Review by draknyte1 — CHANGES_REQUESTED** [review]
No. 

GTNH already did this and did it much better. Please check their fork and port their code instead of writing your own in future.

**Comment by draknyte1** [comment]
Nothing in this PR touches GUIs and it has unnecessary formatting changes.

**Comment by Blood-Asp** [comment]
@draknyte1 at the end is an changed gui png.

**Comment by Blood-Asp** [comment]
and it might help to point to the place in the GTNH repo where they already fixed it if you know of it you should be able to find it much quicker.

**Comment by draknyte1** [comment]
> @draknyte1 at the end is an changed gui png.

Doesn’t show that on mobile. Binary diff unavailable. 


In regards to where, anyone with any intellect would go look at the classes you know must have been changed and check their commit history. If you can’t do this, I don’t want your shit tier PRs. 🤔

**Pull request closed without merging**
