### PR TITLE
Fix overflow when charging ultimate battery

### PR DESCRIPTION
**Pull request by Antifluxfield**

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Antifluxfield die we need it for gtnh too?

**Comment by Antifluxfield** [comment]
@Dream-Master Yes.

**Comment by Dream-Master** [comment]
@Antifluxfield can you add a patch for us?

**Comment by Antifluxfield** [comment]
@Dream-Master https://github.com/GTNewHorizons/GT5-Unofficial/pull/49

**Review by draknyte1 — APPROVED** [review]

**Pull request merged**
