### PR TITLE
Trying to fix PE polymerizing recipe

### PR DESCRIPTION
**Pull request by Antifluxfield**
These recipes collided with the PE polymerizing recipe with oxygen.
I add an Integrated Circuit to distinguish them. Do you have any better idea?

### CODE REVIEW

**Comment by JohannesGaessler** [comment]
I don't think there's a better approach other than adding integrated circuits.
Is there a reason why you disabled the recipe with only cells?

**Comment by Antifluxfield** [comment]
That recipe collides with the PE recipe in the Large Chemical Reactor.

**Comment by Antifluxfield** [comment]
We can fix the third recipe with that simple boolean. But I think we'd better add those methods to sustain their consistency.
If you think adding those things is OK, then all the work is done.

**Comment by Antifluxfield** [comment]
Revert last commits; now using another individual method to add recipes only to the basic Chemical Reactors, trying to evade some potential conflicts.

**Pull request merged**
