### PR TITLE
Fixed Power injection for Multiblocks.

### PR DESCRIPTION
**Pull request by draknyte1**
All Energy Producing Multis will explode if they cannot handle the output load.
All Energy Producing Multis also now support multi amp dynamo hatches, which may be added by addons.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@draknyte1 is this code for GTNH GT too ?

**Comment by draknyte1** [comment]
No. 

It *Is* the NH code. 
Which is a slightly modified version of my original code.

**Comment by Dream-Master** [comment]
ok

**Comment by Dream-Master** [comment]
ok

**Pull request merged**
