### PR TITLE
Adds machines for LuV to UV

### PR DESCRIPTION
**Pull request by mura3277**
Also adds Naquadah-Alloy and Fluxed Electrum wires for ZPM and UV voltages respectively.

This idea for what materials to use for these wires is inspired from @Dream-Master's MCHorizons core mod.

### CODE REVIEW

**Comment by mura3277** [comment]
If there is anything else you want me to do or fix with this PR then just let me know.

**Comment by mura3277** [comment]
Changes:
IV Wire: Changed from Tungsten to Platinum
LuV Wire: Changed from Osmium to NiobiumTitanium
Rotors: Changed LuV-UV rotor materials from Tungsten to the materials for their tier.

**Comment by Blood-Asp** [comment]
Your PR removed a few past changes. I readded them.

**Comment by mura3277** [comment]
Huh, I swear I checked that. Anyway sorry about that.

**Comment by Blood-Asp** [comment]
Also, naquadah alloy and fluxed electrum are missing the recipes by default. Guess i have to add them too. And the changes materials for hulls must be changed too for the machine crafting recipes of them.

**Comment by mura3277** [comment]
I did mention that it wasn't totally done. This was just how far I got adding the new machines. You also don't have to settle on those materials for the new cables, it was just good choices considering adding new materials is a problem.

**Comment by Blood-Asp** [comment]
The naquadah alloy is fine, fluxed electrum might have an better alternative. Else in most cases with thermal expansion installed it is far too easy to get and unbalanced that way.

I mentions the machine crafting recipes since they are easily missed.

**Pull request merged**
