### PR TITLE
Silk-touch then pulverize ores in advanced miner II

### PR DESCRIPTION
**Pull request by perkinslr**

### CODE REVIEW

**Comment by Techlone** [comment]
You removed all changes from #536 Why?

**Comment by perkinslr** [comment]
Because I made these changes before #536 got merged and I missed seeing it in my review of what's changed.  It wouldn't cleanly apply here, but I just merged what will and reimplemented the non-null check.

**Comment by Techlone** [comment]
okay

**Comment by Techlone** [comment]
Nonono
Null check not there. I think so that player or something else can destroy block after adding chunk coords data and block will be null. You should write null check after [this](https://github.com/perkinslr/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_AdvMiner2.java#L139). `tMineBlock != null`

**Comment by perkinslr** [comment]
But that block will never be null.  It might be Blocks.air, and it might not have a TileEntity, but the block itself will never be null.  Unless you're saying that if it is null this pass should automatically move on to the next block in the list... That make sense.

**Comment by Dream-Master** [comment]
Using this code throw out some error.

```
Error:(142, 72) java: cannot find symbol
  symbol:   variable mle
  location: class gregtech.common.tileentities.machines.multi.GT_MetaTileEntity_AdvMiner2
```

https://www.dropbox.com/s/pyivj6sjc16om5d/Screenshot%202016-06-26%2021.40.02.png?dl=0

**Comment by mura3277** [comment]
The issue is mle is not in the same scope as the methods using it.

**Comment by Dream-Master** [comment]
means what? Sorry i am a java noob. How to fix that ?

**Comment by mura3277** [comment]
Compare to see the change https://github.com/Muramasa-/GT5-Unofficial/tree/Temp

**Comment by Dream-Master** [comment]
@Muramasa 
like this when i compare both files ?
https://github.com/GTNewHorizons/GT5-Unofficial/commit/3d9a779242d3611b1d4da5a0c8b218e0708bbf4a

**Comment by mura3277** [comment]
Yep. It's untested of course but it will at least compile. However I can't see there being any issues.

**Comment by Dream-Master** [comment]
Ok thanks

**Pull request merged**
