### PR TITLE
Cracking followup 2

### PR DESCRIPTION
**Pull request by JohannesGaessler**
Currently there are 11 Materials that can be cracked, resulting in 66 recipes with 6 recipes per material.
However, for several materials this level of complexity is not necessary and the amount of infrastructure needed for cracking is too expensive compared to the benefits.

This PR removes Cracking for the Following Materials:

* ~~Refinery Gas~~
* Ethylene
* Propene
* Butene
* Butadiene

Instead this PR adds the following conversions:

* Ethane <-> Ethylene + Hydrogen
* Ethylene <-> Propene
* Propane <-> Propene + Hydrogen
* Ethylene <-> Butene
* Butane <-> Butene + Hydrogen
* Butene <-> Butadiene + Hydrogen

These recipes would also allow the (inefficient) production of plastics from Natural Gas.

This PR also reduces the processing time of the Oil Cracking Unit by a factor of 2.

I also fixed a bug where I forgot to increase the processing time of cracking in a (Large) Chemical Reactor in an earlier PR.

I also increased the yield of cracking Heavy Fuel, Light Fuel, and Naphtha.
It seems I made a mistake when I calculated the appropriate yields for those materials, which resulted in the yields being too low.
For instance, cracking Heavy Fuel into Light Fuel did not actually yield net energy compared to just burning the Heavy Fuel in a Large Boiler.

### CODE REVIEW

**Comment by Antillar** [comment]
I dislike that refinery gas can no longer be cracked. Steam-cracking of refinery gas was a useful way of getting the useful hydrocarbons. I do not really get the point of moderate cracking, but light cracking gave 2566 methane, 213 ethylene and 113 propene, all of them being useful, and the only useless material was ethane, which was only obtained in the amount of 19 mb per operation. Severe cracking gave maximal methane output - 914 methane and only 48 not methane. Additionally, this was a good source of helium used for crystalprocessors and Nq alloy without the need to get to the End and mine stone.

I aspecially like the ability to create butadiene (SBR) from useless butene 1:1

I may be mistaken, but I have not seen butane obtained from steam-cracking completely, also not seen any direct usage of it.

Related issues: https://github.com/Blood-Asp/GT5-Unofficial/issues/1268 https://github.com/Blood-Asp/GT5-Unofficial/issues/1282

**Comment by JohannesGaessler** [comment]
@Antillar Right, I didn't consider that useage of that recipe.
I'll proably reenable it.

**Comment by Antillar** [comment]
I also suggest removing the naphta, light fuel and heavy fuel outputs from distilling cracked naphta, light fuel and heavy fuel. This is unnecessary recursion IMO. I don't see the need of obtaining one from another, as none of them can be used for something special (except naphta being epoxy component in remaining deprecated recipe). The severity of cracking wisely chosen on the following stage can totally neglect the unusual requirement of special hydrocarbons obtained from each of these oil fractions.

Another thing I would like to see is the ability to recycle **acetone** to other hydrocarbons. I have found this: "On distillation with sulphuric acid (H2SO4), it is converted into mesitylene C9H12 (symmetrical trimethyl benzene)." [(source)](http://www.worldofmolecules.com/solvents/acetone.htm)
And that hydrocarbon can further be broken down to useful ones, likely, benzene and methane?
The reason behind this is that for every mb of epoxy produced there is 1 mb of acetone remaining unused. This allows to recycle it further.

**Comment by JohannesGaessler** [comment]
I don't think the feedback loops between Naphtha, Light Fuel, and Heavy Fuels should be removed.
They incentivize building more infrastructure to get better efficiency in terms of Oil.

>The severity of cracking wisely chosen on the following stage can totally neglect the unusual requirement of special hydrocarbons obtained from each of these oil fractions.

I don't understand what you're trying to tell me here.

>On distillation with sulphuric acid (H2SO4), it is converted into mesitylene C9H12 (symmetrical trimethyl benzene)

I think that solution would be overly complicated.
Do you think it would be enough to allow the burning of Acetone in a Gas Turbine?

**Comment by Antillar** [comment]
I think that sorting output from distilled cracked naphta, LF and HF and putting these 3 products back into OCUs does not make the overall infrastructure bigger, only adding extra piping required to connect both
3,3-graphs. 
In my particular case I store all fluids in ME network, so I really do not care where the fluid came from, I just export it to a certain machine.

The reason I am against excessive acetone in epoxy chain is that acetone can only be converted into useless glue or cetane-boosted diesel, and first one can be obtained from LV centrifuge processing Sticky Resin, while the second one is unlikely used by any player, because it simply burns precious oil, which is so expensive to fully process into resins. I admit that once in a while someone appears to prove me wrong, but these are mostly temporary setups, originated from the lack of energy in one place.

What I do with acetone is to break it into hydrogen and carbon, but this way for each mb of epoxy processed from hydrocarbons I waste a whole 1 mb of hydrocarbons as acetone. So I was trying to suggest a way to recycle acetone into hydrocarbons, so the epoxy chain is wasteless.

**Comment by JohannesGaessler** [comment]
Regarding feedback:
The minimal setup for Cracking with a Distillation Tower is to distill Steam-Cracked Naphtha.
If you then get more Light Fuel/Heavy Fuel from that process it gives you a synergy with processing those other Oil products.
You're cracking everything anyways from what I remember from your screenshots.

Regarding Acetone:
What if I were to add more recipes that let you specifically produce Phenol (from Benzene)?

**Comment by Antillar** [comment]
I think, when phenol can be produced separately, the player can produce 2x phenol + 2x acetone by current recipe and 1x separate phenol, and then turn it into wasteless epoxy. Sounds great.

**Pull request merged**
