### PR TITLE
Re-add single-use batteries

### PR DESCRIPTION
**Pull request by Timeslice42**
How did this get removed? ><

Also, can I get a test build of this?

### CODE REVIEW

**Comment by Blood-Asp** [comment]
I guess a merge somehow overwrote it...

**Comment by Blood-Asp** [comment]
Uploaded .27pre build with merged code.

**Comment by Timeslice42** [comment]
Thank you :)

**Comment by Timeslice42** [comment]
This isn't working in 5.09.27pre, are you sure you built the right version?

**Pull request merged**
