### PR TITLE
Fix pipe behaviors

### LINKED ISSUE #1301: GT6 Styled Pipes & Cables: OpenGL Error
After the update, an error occurs when connecting pipes.

### LINKED ISSUE #1313: GT6 Style Pipes - Misrouting
Preface: I haven't specifically tested on this repository; however I believe the downstream GTNH repo has basically the same code.  Also reported at https://github.com/GTNewHorizons/GT5-Unofficial/issues/59

I've been playing with a self compiled version (from the GTNH fork) from github and noticed the GT6 style pipes mis-route items when adjacent to a machine/chest.

In the image below, I'd expect the items to route from 1 --> 2 --> 3 (green path).  
However, without any paper between the pipe and 2, the items will route 1 --> 2 --> 2 (red path).  

If I paper the pipe or the chest buffer, it will then route 1 --> 2 --> 1 (pink path)

pipe misrouting

### LINKED ISSUE #1327: [5.09.32pre1] Fluid pipes dont connect
Fluid pipes don't connect after closing shutter module with machine controller.
shutter

### LINKED ISSUE #1331: GT6 Style Wires
If you restart the server after you connect the wires, all connections will be reset

### LINKED ISSUE #1333: GT6 Style Pipes - Compatibility with other mods
Pipes don't connect to tanks from other mods.
post-75725-0-54196300-1513210832

### PR DESCRIPTION
**Pull request by Antifluxfield**
Fix #1313 
Fix #1327 
Fix #1333 
Fix #1331 
Fix #1301

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Antifluxfield are you able to pull it to GTNH too?

**Comment by Antifluxfield** [comment]
@Dream-Master Just working for it

**Comment by Dream-Master** [comment]
Ok cool. Thanks

**Review by draknyte1 — APPROVED** [review]
Works as far as I could test. Cheers mate.

**Comment by Antifluxfield** [comment]
:beers:

**Pull request merged**
